### PR TITLE
feat: :sparkles: YouTube Playlist Component

### LINKED ISSUE #17: Youtube Playlist
## Overview
Create a component to embed the Tuesday's Tunes YouTube playlist.
https://www.youtube.com/watch?v=qRskZcB5Rbc&list=PLrY8SmqJ5XZ_UvVurEvGg8i10g-cxMudZ&ab_channel=AnalogStudiosRI

Image

## Requirements
1. [ ] Embed playlist into a component
1. [ ] Storybook
1. [ ] Spec
1. [ ] Try and have most recent episode show up first
1. [ ] See if we can theme it

### PR DESCRIPTION
**Pull request by Omafovbe**
Created a component to accommodate listing the youtube playlist. for now just the images and their titles.

## Related Issue
resolves #17

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Hey @Omafovbe , thanks for the PR!

Would it be possible to see this in a Storybook?  That would be really helpful for review and testing.  You can see how the [Footer component](https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/tree/v1/src/components/footer) is structured to get an idea of how to set things up.

Left some feedback in-line and also a couple minor observations (no big deal, I can always clean these up before merge)
- If you run `yarn lint` it should help give you some feedback on indentation fixes to help us keep our code formatting a bit more consistent
- I would avoid abberviations, I think it's fine to spell out the whole file / variable name, e.g. _src/components/youtube-playlist/youtube-playlist.js_
- This project uses Yarn, so I would make sure you have run `yarn install`.  We can delete _package-lock.json_ from this PR

Thanks for the good start, let me know if you have any questions!

**Comment by Omafovbe** [comment]
In relation to all of the comments you made on the first PR, I have done some update
1. Updated the yt-playlist branch from feature/cast-and-crew branch
2. Carried out all of suggestions (hope I didn't miss any one)
3. Create storybook files to help preview the updates and changes
4. I really don't know how to manage the YouTube channel ID on storybook

Please let me know if there is anything I missed and need updating. Thanks

**Comment by Omafovbe** [comment]
Thanks for the comment. Just saw the feature/cast-and-crew branch has more
packages installed than the main or v1 branch. Guess moving forward I would
create a branch off the feature branch and that's why some of my code looks
somewhat different.
For the corrections would surely, take that into account and improve on the
PR. Thanks

**Review by thescientist13 — COMMENTED** [review]
Hey @Omafovbe , thanks for your work here and providing the different samples.

I think we should have an `<iframe>` embed version to compare with, just so we can see what a "live" list version might look like just coming straight from YouTube.  That could be the simplest to start out with for now and then maybe we could evolve the implementation together in follow up PRs?  But for now, let's just compare both options (`<iframe>` vs API call) just so we can learn what the pros / cons of each approach might be.

Also, we would want to specifically use the playlist from the issue, as that is a playlist from our channel specific to our Tuesday's Tunes show.  So basically, the embed version should probably look something like
```html
<iframe src="https://www.youtube.com/watch?v=qRskZcB5Rbc&list=PLrY8SmqJ5XZ_UvVurEvGg8i10g-cxMudZ" ...>
```

Here are the docs from YouTube to help give you an idea of what might be possible with that option.
https://developers.google.com/youtube/player_parameters


----

As a note on branch management, I would just focus on maintaining a reference to only what is in the v1 branch.  Each PR only has to focus on one task of work, so no need to mix and match work from other PRs.  If you could just make sure your branch is coming from v1 and doesn't have any other code other than the YT work, that will make sure reviewing (and merging!) is much easier for each of us.

Thanks again for your help!  :peace:

**Review by thescientist13 — COMMENTED** [review]
Let me know if you need any help finishing this up.  There was a PR opened for the Spotify player which should give you a good reference for what we can do for now in this PR.  So basically just cleaning up the extra files and just using the `<iframe>` for now. - https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/pull/43

I did make a ticket to track a more long term solution for building our players so if you have any thoughts / ideas on that approach, feel free to comment! - https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/issues/45

**Comment by Omafovbe** [comment]
Oh thanks. Sorry about not going about the update from last PR. Was busy
over the weekend but should work  on it this week and send a PR will surely
look into the stripe thingy and use that as a reference

**Review by thescientist13 — APPROVED** [review]
Thanks for your help with this @Omafovbe ! 🙌 

Going to keep it as an `<iframe>` for now and will think about other ways to enhance this as you had originally suggested, I like the idea of us creating a first party playlist for this component.

Feel free to jump into any other tasks you might find, I'll be making a few more issues over the next couple days and so some of those should be good first issue types as well.

**Pull request merged**
