### PR TITLE
Align upcoming events

### PR DESCRIPTION
**Pull request by Majiedo**
## Related Issue

this change resloves #57

## Summary of Changes

addiung to `h4` tag flex property and adding `span` tag height (1.6rem) which i see the most close to the design, and margin right (0.5rem)

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Thanks for this @Majiedo !

It looks like there is an issue rendering the custom element due to the switch of using template strings, so I don't the upcoming events locally or in the preview environment.  (This looks like a verified [bug in **WCC**](https://github.com/ProjectEvergreen/wcc/issues/97))

That said, not sure if it is your IDE doing the formatting, but if you could revert all the formatting changes in this PR, that would be appreciated.  ESLint should keep most things in check, if you run `yarn lint`.  I think with out all the extra noise from those diffs, it will be easier to review what is going on in this PR.

Thanks!

**Comment by Majiedo** [comment]
it should be work right now let me know if there's anything wrong i could fix it 

- Thanks

**Comment by thescientist13** [comment]
Hey @Majiedo , what do you see if you run `yarn lint` locally?  I tested your branch locally and saw the same errors reported as the ones here by GitHub Actions.
```sh
 % yarn lint
yarn run v1.22.5
$ ls-lint && yarn lint:js && yarn lint:css
$ eslint "*.{js,cjs,.mjs}" ".storybook/*.{js,cjs}" "src/**/**/*.js"

/Users/owenbuckley/Desktop/www.tuesdaystunes.tv/src/components/footer/footer.spec.js
  82:7  warning  Unexpected 'todo' comment: 'TODO actually get this match against a...'   no-warning-comments
  82:7  warning  Unexpected ' TODO' comment: 'TODO actually get this match against a...'  no-warning-comments

/Users/owenbuckley/Desktop/www.tuesdaystunes.tv/src/components/upcoming-events/upcoming-events.js
  36:1   error    Expected indentation of 6 spaces but found 8  indent
  37:1   error    Expected indentation of 6 spaces but found 8  indent
  77:70  warning  Unexpected 'todo' comment: 'TODO...'          no-warning-comments
  77:70  warning  Unexpected ' TODO' comment: 'TODO...'         no-warning-comments

/Users/owenbuckley/Desktop/www.tuesdaystunes.tv/src/pages/index.js
  9:5  warning  Unexpected 'todo' comment: 'TODO figure out how to filter for events...'   no-warning-comments
  9:5  warning  Unexpected ' TODO' comment: 'TODO figure out how to filter for events...'  no-warning-comments

✖ 8 problems (2 errors, 6 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

Maybe I can help debug your local environment if you are not seeing the same thing?

**Comment by Majiedo** [comment]
how can i run the `--fix`? this is my first time work with eslint i get the same thing when i run `yarn lint`

**Comment by thescientist13** [comment]
I usually just make the changes manually, as `--fix` might not work for all issue.  But you can try by running it like this
```sh
$ yarn lint --fix
```

**Comment by thescientist13** [comment]
No, just the errors please.  (The warnings should just be `TODO` comments I've left behind.)

**Comment by Majiedo** [comment]
alright i'll work on it right now it, you should expect PR in any minutes

**Comment by Majiedo** [comment]
it should everything works now, in my local environment this is what i get when i run `yarn lint`

image

**Comment by thescientist13** [comment]
Thanks, I'll catch up on this over the weekend.  👍

**Comment by thescientist13** [comment]
In general though for future commits, do you mind turning off any formatting in your IDE?  There still seems to be a lot of formatting only related changes which are adding extra diff lines unfortunately, but I can work through it for now when I follow up.  thanks!

**Comment by Majiedo** [comment]
yes sure! will do!

**Review by thescientist13 — APPROVED** [review]
Thanks @Majiedo !

I cleaned up a bit of the formatting to what it was before just to help with readability here, and so all looks good now!

**Pull request merged**
